name: complex
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2024.3.11=h06a4308_0
  - cudatoolkit=11.8.0=h6a678d5_0
  - cudnn=8.9.2.26=cuda11_0
  - ld_impl_linux-64=2.38=h1181459_1
  - libffi=3.4.4=h6a678d5_0
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.13=h7f8727e_0
  - pip=23.3.1=py38h06a4308_0
  - python=3.8.19=h955ad1f_0
  - readline=8.2=h5eee18b_0
  - setuptools=68.2.2=py38h06a4308_0
  - sqlite=3.41.2=h5eee18b_0
  - tk=8.6.12=h1ccaba5_0
  - wheel=0.41.2=py38h06a4308_0
  - xz=5.4.6=h5eee18b_0
  - zlib=1.2.13=h5eee18b_0
  - pip:
      - absl-py==2.1.0
      - cachetools==5.3.3
      - certifi==2024.2.2
      - charset-normalizer==3.3.2
      - google-auth==2.29.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.62.1
      - idna==3.6
      - importlib-metadata==7.1.0
      - jinja2==3.1.3
      - llvmlite==0.41.1
      - markdown==3.6
      - markupsafe==2.1.5
      - numba==0.58.1
      - numpy==1.24.4
      - oauthlib==3.2.2
      - protobuf==5.26.0
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pyparsing==3.1.2
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - rsa==4.9
      - six==1.16.0
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - torch==1.12.0+cu116
      - torch-cluster==1.6.0+pt112cu116
      - torch-geometric==2.1.0.post1
      - torch-scatter==2.0.9
      - torch-sparse==0.6.15+pt112cu116
      - torch-spline-conv==1.2.1+pt112cu116
      - tqdm==4.66.2
      - typing-extensions==4.10.0
      - urllib3==2.2.1
      - werkzeug==3.0.1
      - zipp==3.18.1
prefix: /home/zhc/anaconda3/envs/complex
